spring.application.name=green-login-be

# --- APPLICATION CONFIG ---
server.port=${APP_PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- DATABASE CONFIG (PostgreSQL) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- FLYWAY CONFIG ---
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.baseline-on-migrate=true

# --- JWT CONFIG ---
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# --- MAIL CONFIG ---
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# --- VNPAY CONFIG ---
vnpay.tmn-code=${VNPAY_TMN_CODE:QXST4W8X}
vnpay.hash-secret=${VNPAY_HASH_SECRET:77BXF1LE6HAC9KHPBI7QL20GV96GB87P}
vnpay.pay-url=${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:8080/api/vnpay/payment-callback}
vnpay.frontend-result-url=${VNPAY_FRONTEND_RESULT_URL:http://localhost:5173/payment-result}
